### ISSUE TITLE
first issue

### ISSUE THREAD

**Issue by zdmelon** [HarrisonLin/RecyclerViewEffectGather#1]
有个问题，初始化有层黑色背景，滑动后消失

**Comment by Deepblue1996** [comment]
的确,我也存在

**Comment by Deepblue1996** [comment]
问题已解决, 我这里就不说解为什么, 把保存图层那段代码改成
layerId = c.saveLayer(0.0f, 0.0f, (float) parent.getWidth(), (float) parent.getHeight()
                                , null, Canvas.ALL_SAVE_FLAG);
